module.exports = {
	apiUrl: "https://api.fitbit.com",
	oauth2TokenEndpoint: "/oauth2/token",
	grantTypeAuthorizationCode: "authorization_code",
	grantTypeRefreshToken: "refresh_token",
	contentType: "application/x-www-form-urlencoded",
	requestType: {
		heart: "activities/heart",
		activeZoneMinutes: "activities/active-zone-minutes",
		calories: "activities/calories",
		distance: "activities/distance",
		elevation: "activities/elevation",
		floors: "activities/floors",
		steps: "activities/steps",
		breathingRate: "br",
		heartRateVariability: "hrv",
		spO2: "spo2",
		foodLogsCalories: "foods/log/caloriesIn",
		foodLogsWater: "foods/log/water",
		favoriteFoods: "foods/log/favorite",
		frequentFoods: "foods/log/frequent",
		recentFoods: "foods/log/recent",
		foodGoals: "foods/log/goal",
		foodWaterGoals: "foods/log/water/goal",
		meals: "meals",
		foodSummaryByDate: "foods/log/date",
		foodWaterSummaryByDate: "foods/log/water/date",
		bodyBmi: "body/bmi",
		bodyFat: "body/fat",
		bodyWeight: "body/weight",
		bodyFatGoals: "body/log/weight/goal",
		bodyWeightGoals: "body/log/fat/goal",
		bodyFatSummaryByDate: "body/log/fat/date",
		bodyWeightSummaryByDate: "body/log/weight/date",
		activityStatistics: "activities",
		activitySummaryByDate: "activities/date",
		activityGoals: "activities/goals/daily",
		activityLogList: "activities/list",
		favoriteActivities: "activities/favorite",
		frequentActivities: "activities/frequent",
		recentActivities: "activities/recent",
	},
	detailLevel: {
		oneSecond: "1sec",
		oneMinute: "1min"
	}
};