module.exports = {
	apiUrl: "https://api.fitbit.com",
	oauth2TokenEndpoint: "/oauth2/token",
	grantTypeAuthorizationCode: "authorization_code",
	grantTypeRefreshToken: "refresh_token",
	contentType: "application/x-www-form-urlencoded",
	debug: true,
	resource: {
		heart: { requestType: "activities/heart", scope: "heartrate", enabled: true },
		activeZoneMinutes: { requestType: "activities/active-zone-minutes", scope: "activity", enabled: true },
		calories: { requestType: "activities/calories", scope: "activity", enabled: true },
		distance: { requestType: "activities/distance", scope: "activity", enabled: true },
		elevation: { requestType: "activities/elevation", scope: "activity", enabled: true },
		floors: { requestType: "activities/floors", scope: "activity", enabled: true },
		steps: { requestType: "activities/steps", scope: "activity", enabled: true },
		breathingRate: { requestType: "br", scope: "respiratory_rate", enabled: true },
		heartRateVariability: { requestType: "hrv", scope: "respiratory_rate", enabled: true },
		spO2: { requestType: "spo2", scope: "oxygen_saturation", enabled: true },
		foodLogsCalories: { requestType: "foods/log/caloriesIn", scope: "nutrition", enabled: true },
		foodLogsWater: { requestType: "foods/log/water", scope: "nutrition", enabled: true },
		favoriteFoods: { requestType: "foods/log/favorite", scope: "nutrition", enabled: true },
		frequentFoods: { requestType: "foods/log/frequent", scope: "nutrition", enabled: true },
		recentFoods: { requestType: "foods/log/recent", scope: "nutrition", enabled: true },
		foodGoals: { requestType: "foods/log/goal", scope: "nutrition", enabled: true },
		foodWaterGoals: { requestType: "foods/log/water/goal", scope: "nutrition", enabled: true },
		meals: { requestType: "meals", scope: "nutrition", enabled: true },
		foodSummaryByDate: { requestType: "foods/log/date", scope: "nutrition", enabled: true },
		foodWaterSummaryByDate: { requestType: "foods/log/water/date", scope: "nutrition", enabled: true },
		bodyBmi: { requestType: "body/bmi", scope: "weight", enabled: true },
		bodyFat: { requestType: "body/fat", scope: "weight", enabled: true },
		bodyWeight: { requestType: "body/weight", scope: "weight", enabled: true },
		bodyFatGoals: { requestType: "body/log/weight/goal", scope: "weight", enabled: true },
		bodyWeightGoals: { requestType: "body/log/fat/goal", scope: "weight", enabled: true },
		bodyFatSummaryByDate: { requestType: "body/log/fat/date", scope: "weight", enabled: true },
		bodyWeightSummaryByDate: { requestType: "body/log/weight/date", scope: "weight", enabled: true },
		activityStatistics: { requestType: "activities", scope: "activity", enabled: true },
		activitySummaryByDate: { requestType: "activities/date", scope: "activity", enabled: true },
		activityGoals: { requestType: "activities/goals/daily", scope: "activity", enabled: true },
		activityLogList: { requestType: "activities/list", scope: "activity", enabled: true },
		favoriteActivities: { requestType: "activities/favorite", scope: "activity", enabled: true },
		frequentActivities: { requestType: "activities/frequent", scope: "activity", enabled: true },
		recentActivities: { requestType: "activities/recent", scope: "activity", enabled: true },
		cardioFitnessScore: { requestType: "cardioscore", scope: "cardio_fitness", enabled: true },
		sleep: { requestType: "sleep", scope: "sleep", enabled: true },
		sleepGoals: { requestType: "sleep/goal", scope: "sleep", enabled: true },
		coreTemperatureByDate: { requestType: "temp/core/date", scope: "temperature", enabled: true },
		skinTemperatureByDate: { requestType: "temp/skin/date", scope: "temperature", enabled: true },
		electrocardiogram: { requestType: "ecg/list", scope: "electrocardiogram", enabled: true },
		profile: { requestType: "profile", scope: "profile", enabled: true },
		devices: { requestType: "devices", scope: "profile", enabled: true },
		friends: { requestType: "friends", scope: "social", enabled: true }
	},
	detailLevel: {
		oneSecond: "1sec",
		oneMinute: "1min"
	}
};